name: Legitify Scan (PAT)

on: [workflow_dispatch]

jobs:
  scan-repository:
    name: Scan Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan Repo
        uses: Legit-Labs/legitify@b814483c588aefad01b33e921008e73352639277
        with:
          github_token: ${{ secrets.GH_PAT }}
          analyze_self_only: "true"
          scorecard: verbose
      - name: List Content
        if: always()
        run: ls
          
    
